name = "smartmeetings-sync"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[[d1_databases]]
binding = "DB"
database_name = "smartmeetings-db"
database_id = "94fb37b9-79e3-4d55-af62-e0c3446e82f4"
